// src/utils/coinGeckoMap.js

export const coinIdMap = {
  BTC: 'bitcoin',
  ETH: 'ethereum',
  BNB: 'binancecoin',
  USDT: 'tether',
  XRP: 'ripple',
  SOL: 'solana',
  ADA: 'cardano',
  DOGE: 'dogecoin',
  DOT: 'polkadot',
  MATIC: 'matic-network',
  SHIB: 'shiba-inu',
  LTC: 'litecoin',
  TRX: 'tron',
  AVAX: 'avalanche-2',
  CRO: 'cronos',
  LINK: 'chainlink',
  BCH: 'bitcoin-cash',
  XLM: 'stellar',
  ETC: 'ethereum-classic',
  FIL: 'filecoin',
  EOS: 'eos', // ✅ keep only one
  APE: 'apecoin',
  ATOM: 'cosmos',
  NEAR: 'near',
  MANA: 'decentraland',
  SUSHI: 'sushi',
  AAVE: 'aave',
  ICP: 'internet-computer',
  LUNC: 'terra-luna-2',
  TON: 'toncoin',
  FTM: 'fantom',
  VET: 'vechain',
  HBAR: 'hedera-hashgraph',
  XMR: 'monero',
  QNT: 'quant-network',
  AR: 'arweave',
  AXS: 'axie-infinity',
  GRT: 'the-graph',
  THETA: 'theta-token',
  GMT: 'stepn',
}
